/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programasps.frontend;

import java.awt.Toolkit;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import programasps.backend.koneksiData;

/**
 *
 * @author dnrahmath
 */
public class AaHomePanel extends JFrame {

    /**
     * Creates new form AaGuestPanel
     */
    
    //background color
    Color colorBackground = new Color(255, 255, 204, 255);
    //Color colorBackgroundForm = new Color(255, 255, 204, 255);
    Color colorBackgroundForm = new Color(255, 210, 185, 255); //jika mau liat batas panelnya
    
    
    //waktu saat ini
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
    LocalDateTime now = LocalDateTime.now();  
    
    
    String[][] DataLogin;
    
    public AaHomePanel() {
        initComponents();
        this.setExtendedState(AaHomePanel.MAXIMIZED_BOTH);
        
        panelJudul1.setBackground(colorBackgroundForm);
        panelJudul2.setBackground(colorBackgroundForm);
        panelIsi1.setBackground(colorBackgroundForm);
        panelBtn1.setBackground(colorBackgroundForm);
        panelBtn2.setBackground(colorBackgroundForm);
    }
    
    void submitDataFunc(){
        String[] listColmn = {
            "id",
            "nama",
            "asal",
            "catatan",
            "tanggal",
        };

        String[] listColmnRow = {
            "0",
            txtnmtamu.getText(),
            txtasaltamu.getText(),
            txtcttntamu.getText(),
            dtf.format(now),
        };
        koneksiData conn = new koneksiData();
        conn.cInsert("tbl_tamu",listColmn,listColmnRow);

        txtnmtamu.setText("");
        txtasaltamu.setText("");
        txtcttntamu.setText("");

        CaMenuCariBuku mCB = new CaMenuCariBuku(colorBackground,colorBackgroundForm);
        mCB.setDefaultCloseOperation(mCB.DISPOSE_ON_CLOSE);
        mCB.setLocationRelativeTo(null);

        mCB.setVisible(true);
    };
    
    void exceptionSubmit(){
        JOptionPane widgetQuestion = new JOptionPane();
        int jawab = widgetQuestion.showOptionDialog(this, 
                "Apakah Kamu yakin?", 
                "Submit", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        switch(jawab){
            case JOptionPane.YES_OPTION: 
                submitDataFunc();
                break;
            case JOptionPane.NO_OPTION:
                txtnmtamu.setText("");
                txtasaltamu.setText("");
                txtcttntamu.setText("");
                txtnmtamu.requestFocusInWindow();
                break;
        }
    };
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTamu = new javax.swing.JPanel();
        panelJudul1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelIsi1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtasaltamu = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtnmtamu = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcttntamu = new javax.swing.JTextArea();
        btnTamuSubmit = new javax.swing.JButton();
        panelBtn2 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        panelBtn1 = new javax.swing.JPanel();
        btnTamuSdhIsi = new javax.swing.JButton();
        panelJudul2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTamu.setBackground(new java.awt.Color(255, 255, 204));

        panelJudul1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel11.setText("untuk pendataan alur pinjam buku pada SMA Kharismawita  ");

        jLabel26.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel26.setText("Perancangan dan Pengembangan ASPS (Aplikasi Sistem Perpustakaan Sekolah)");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programasps/images/logo-Kharismawita-85px.png"))); // NOI18N

        javax.swing.GroupLayout panelJudul1Layout = new javax.swing.GroupLayout(panelJudul1);
        panelJudul1.setLayout(panelJudul1Layout);
        panelJudul1Layout.setHorizontalGroup(
            panelJudul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudul1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel26)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelJudul1Layout.createSequentialGroup()
                .addGroup(panelJudul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJudul1Layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jLabel3))
                    .addGroup(panelJudul1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJudul1Layout.setVerticalGroup(
            panelJudul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudul1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelIsi1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel17.setText(" :");

        txtasaltamu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtasaltamuKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel18.setText("Asal / Kelas");

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel19.setText("Nama");

        jLabel20.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel20.setText(" :");

        txtnmtamu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnmtamuKeyPressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel22.setText("Catatan");

        jLabel23.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel23.setText(" :");

        txtcttntamu.setColumns(20);
        txtcttntamu.setRows(5);
        txtcttntamu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcttntamuKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtcttntamu);

        btnTamuSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnTamuSubmit.setText("SUBMIT");
        btnTamuSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamuSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIsi1Layout = new javax.swing.GroupLayout(panelIsi1);
        panelIsi1.setLayout(panelIsi1Layout);
        panelIsi1Layout.setHorizontalGroup(
            panelIsi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIsi1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(panelIsi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIsi1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20))
                    .addGroup(panelIsi1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel23))
                    .addGroup(panelIsi1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)))
                .addGroup(panelIsi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIsi1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelIsi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtasaltamu)
                            .addComponent(jScrollPane1)
                            .addGroup(panelIsi1Layout.createSequentialGroup()
                                .addComponent(txtnmtamu, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(107, 107, 107))
                    .addGroup(panelIsi1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnTamuSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelIsi1Layout.setVerticalGroup(
            panelIsi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIsi1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelIsi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(txtnmtamu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIsi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtasaltamu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGroup(panelIsi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIsi1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelIsi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)))
                    .addGroup(panelIsi1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnTamuSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        panelBtn2.setBackground(new java.awt.Color(153, 255, 153));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programasps/images/icon_asps/iloveimg-resized-16/user-interface.png"))); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programasps/images/icon_asps/iloveimg-resized-16/add-user.png"))); // NOI18N
        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel21.setText("Atau");

        panelBtn1.setBackground(new java.awt.Color(153, 255, 153));

        btnTamuSdhIsi.setBackground(new java.awt.Color(255, 255, 255));
        btnTamuSdhIsi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTamuSdhIsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programasps/images/icon_asps/iloveimg-resized-32/research (1).png"))); // NOI18N
        btnTamuSdhIsi.setText("CARI BUKU");
        btnTamuSdhIsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamuSdhIsiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtn1Layout = new javax.swing.GroupLayout(panelBtn1);
        panelBtn1.setLayout(panelBtn1Layout);
        panelBtn1Layout.setHorizontalGroup(
            panelBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtn1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTamuSdhIsi, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        panelBtn1Layout.setVerticalGroup(
            panelBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtn1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnTamuSdhIsi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBtn2Layout = new javax.swing.GroupLayout(panelBtn2);
        panelBtn2.setLayout(panelBtn2Layout);
        panelBtn2Layout.setHorizontalGroup(
            panelBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtn2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel21)
                .addGap(35, 35, 35)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
            .addComponent(panelBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBtn2Layout.setVerticalGroup(
            panelBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtn2Layout.createSequentialGroup()
                .addComponent(panelBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelJudul2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel24.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel24.setText("FORM KUNJUNGAN PERPUSTAKAAN");

        javax.swing.GroupLayout panelJudul2Layout = new javax.swing.GroupLayout(panelJudul2);
        panelJudul2.setLayout(panelJudul2Layout);
        panelJudul2Layout.setHorizontalGroup(
            panelJudul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudul2Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJudul2Layout.setVerticalGroup(
            panelJudul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudul2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programasps/images/icon_asps/iloveimg-resized-16/enter.png"))); // NOI18N
        jButton1.setText("Keluar Aplikasi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTamuLayout = new javax.swing.GroupLayout(panelTamu);
        panelTamu.setLayout(panelTamuLayout);
        panelTamuLayout.setHorizontalGroup(
            panelTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTamuLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(panelTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelIsi1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelJudul2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelJudul1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        panelTamuLayout.setVerticalGroup(
            panelTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTamuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelJudul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelJudul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelIsi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(panelBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTamuLayout.createSequentialGroup()
                .addGap(670, 670, 670)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(359, 359, 359))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTamu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTamu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1477, 1100);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTamuSdhIsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamuSdhIsiActionPerformed
        // TODO add your handling code here:

        CaMenuCariBuku mCB = new CaMenuCariBuku(colorBackground,colorBackgroundForm);
        mCB.setDefaultCloseOperation(mCB.DISPOSE_ON_CLOSE);
        mCB.setLocationRelativeTo(null);

        mCB.setVisible(true);

        //---pindah ke form search book
    }//GEN-LAST:event_btnTamuSdhIsiActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        AaLoginRegisterPanel inRes = new AaLoginRegisterPanel(2,colorBackground,colorBackgroundForm);
        inRes.setDefaultCloseOperation(inRes.EXIT_ON_CLOSE);
        inRes.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        AaLoginRegisterPanel inRes = new AaLoginRegisterPanel(1,colorBackground,colorBackgroundForm);
        inRes.setDefaultCloseOperation(inRes.EXIT_ON_CLOSE);
        inRes.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnTamuSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamuSubmitActionPerformed
        // TODO add your handling code here:
        exceptionSubmit();
    }//GEN-LAST:event_btnTamuSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnmtamuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnmtamuKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
            txtasaltamu.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtnmtamuKeyPressed

    private void txtasaltamuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtasaltamuKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
            txtcttntamu.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtasaltamuKeyPressed

    private void txtcttntamuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcttntamuKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
            exceptionSubmit();
        }
    }//GEN-LAST:event_txtcttntamuKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AaHomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AaHomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AaHomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AaHomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AaHomePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnTamuSdhIsi;
    private javax.swing.JButton btnTamuSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBtn1;
    private javax.swing.JPanel panelBtn2;
    private javax.swing.JPanel panelIsi1;
    private javax.swing.JPanel panelJudul1;
    private javax.swing.JPanel panelJudul2;
    private javax.swing.JPanel panelTamu;
    private javax.swing.JTextField txtasaltamu;
    private javax.swing.JTextArea txtcttntamu;
    private javax.swing.JTextField txtnmtamu;
    // End of variables declaration//GEN-END:variables


}
